<a href="https://colab.research.google.com/github/fininsight/text-mining-tutorial/blob/master/5_%EC%A3%BC%EC%A0%9C%EC%96%B4_%EC%B0%BE%EA%B8%B0_Topic_Modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##LDA

In [0]:
import pandas as pd
from konlpy.tag import Okt
okt = Okt()

from sklearn.feature_extraction.text import TfidfVectorizer

In [0]:
df1 = pd.read_csv('preprocessing_실리콘벨리기사.csv')

In [0]:
df1.rename(columns={'0':'raw','1':'tuned'},inplace=True)

In [0]:
print(df1['raw'].tolist())

['교육을 삶의 최우선 순위로 두고 있는 한국의 부모들은 대학 전공 가운데 의학과 공학·과학을 중시한다. 자녀의 직업적 성공을 위해 대학 전공으로 의학과 이공계를 우선적으로 고려하는 일은 한국이 산업화 중이던 상황에선 올바른 선택이었다. 하지만 지금은 모든 것이 달라졌다. 요즘 실리콘밸리에서 확인되는 것은 4차 산업혁명 시대에는 예술과 인문학이 의학·공학만큼 중요하다는 사실이다.스티브 잡스는 자신이 대학 시절 수강했던 서체(書體) 수업이 매킨토시(애플이 1984년 발표한 개인용 컴퓨터) 개발 성공에 큰 영향을 미쳤다고 말했다. 그는 2011년 아이패드 2를 공개하면서 "애플의 DNA는 기술만으로는 충분하지 않다. 교양과 인문학이 결합한 기술이야말로 가슴 벅찬 결과를 낳을 것"이라며 예술과 디자인의 중요성을 강조했다. 이런 관점을 바탕으로 잡스는 세계 최고 가치를 인정받는 기업을 만들었고, 기술 산업의 새로운 표준까지 정했다.실리콘밸리에서 최근 뜨고 있는 스타 기업인 중에는 인문학 전공자들이 제법 많다. 구인·구직 소셜 네트워킹 서비스 기업인 링크드인(LinkedIn) 창업자 리드 호프만은 철학 석사 학위 소지자이며, 수잔 보이치키 유튜브 CEO는 역사와 문학을 전공했다. 메신저 개발 업체 슬랙(Slack)의 창업자 스튜어트 버터필드는 철학, 세계 최대 숙박 공유 기업인 에어비앤비의 설립자 브라이언 체스키는 미술을 전공했다. 중국 알리바바그룹의 마윈 회장의 학부 전공은 영어였다.내가 속해 있는 하버드대·듀크대 연구팀은 미국 IT 기업 창업자들의 92%가 학사 학위를, 47%는 석사 학위 이상을 갖고 있음을 밝혀냈다. 창업자들의 세부 전공을 보면 37%만 공학·컴퓨터 기술이며, 수학 전공자는 2%뿐이었다. 이들의 전공은 경영·회계·보건·예술·인문학 등 매우 다양했다.컴퓨터 주변기기 제조 업체 로지텍의 브랙큰 대럴 CEO도 영문학을 전공했다. 최근 내가 그에게 "어떻게 5년여 만에 회사 주가를 450% 올릴 수 있었느냐"고 물었더니 그는 "우리 회사가 만드는 모든 제품의 디자인을 쉼 없이 고민했기 때문에 가능했다. 기술 관련 제품의 성공에 가장 중요한 것은 디자인"이라고 답했다.4차 산업혁명은 \'혁신의 규칙\'을 바꾸는 일이다. 여기에는 컴퓨터와 인공지능, 디지털 의술, 로봇공학, 합성생물학 등 광범위한 기술이 활용된다. 의학·인공지능과 센서를 융합하면 인간의 건강을 진단하고 질병을 예방하는 \'디지털 의사\'를 만들 수 있다. 유전체학과 유전자 편집을 이용해 가뭄에 강하고 인류 전체를 먹여 살릴 새 식물을 개발할 수 있다. 인공지능 로봇을 사용해 노인들을 위한 \'디지털 친구\'도 가능하다. 초소형 물질의 발전은 모든 사람이 충분히 이용할 수 있는 \'태양열 저장 기술\'의 새 시대를 열 것이다.이런 해결책을 이끌어내는 데는 생물학·교육·의료·인간행동 등 여러 분야에 대한 지식이 필요하다. 우리가 처한 거대한 사회·기술적 도전에 대처하려면 인류를 둘러싼 다양한 배경과 맥락에 대해 비판적 사고 능력이 필수적이다. 이는 인문학 전공자들이 가장 잘 훈련받은 분야이다.일례로 음악·예술·문학과 심리학에서 비롯한 공감(共感) 능력은 디자인에 큰 장점이 된다. 로마제국의 흥망성쇠와 계몽주의를 공부한 역사학도는 기술의 인간적 요소와 유용성에 대한 통찰력을 가질 수 있다. 심리학 전공자는 사람에게 동기(動機)부여가 무엇이며, 사용자들이 원하는 게 무엇인지를 공학 한 분야에서만 일해온 엔지니어들보다 잘 이해할 수 있다. 우리가 상상하는 물건을 3D로 만들 수 있게 되면 음악가나 화가들의 세상이 될지도 모른다."자녀가 미래에 어떤 직업을 택하면 좋겠는가"라는 질문을 받을 때 나는 "아이들이 스스로 하고 싶은 것을 선택하도록 내버려 두는 게 최선"이라고 답한다. 과거 우리 부모들이 우리에게 공부를 강요해서 학습을 \'억지로 해야 하는 따분한 일\'로 여기게 했던 방식을 따라 해선 안 된다. 그 대신 자녀가 자신의 열정을 추구하고 배우는 걸 즐길 수 있도록 북돋아야 한다.기술을 통해 놀라운 미래를 창조하고 새로운 산업혁명 시대에 리더가 되기 위해 한국에서는 공학자들과 손잡고 일할 음악가와 화가가 더 많이 필요하다. 이제는 과학·공학·의학뿐 아니라 창의성과 디자인에도 진정한 관심을 쏟아야 한다.']

In [0]:
doc = df1['raw'].tolist()
sentences = doc[0].split(".")
sentences

['교육을 삶의 최우선 순위로 두고 있는 한국의 부모들은 대학 전공 가운데 의학과 공학·과학을 중시한다',
 ' 자녀의 직업적 성공을 위해 대학 전공으로 의학과 이공계를 우선적으로 고려하는 일은 한국이 산업화 중이던 상황에선 올바른 선택이었다',
 ' 하지만 지금은 모든 것이 달라졌다',
 ' 요즘 실리콘밸리에서 확인되는 것은 4차 산업혁명 시대에는 예술과 인문학이 의학·공학만큼 중요하다는 사실이다',
 '스티브 잡스는 자신이 대학 시절 수강했던 서체(書體) 수업이 매킨토시(애플이 1984년 발표한 개인용 컴퓨터) 개발 성공에 큰 영향을 미쳤다고 말했다',
 ' 그는 2011년 아이패드 2를 공개하면서 "애플의 DNA는 기술만으로는 충분하지 않다',
 ' 교양과 인문학이 결합한 기술이야말로 가슴 벅찬 결과를 낳을 것"이라며 예술과 디자인의 중요성을 강조했다',
 ' 이런 관점을 바탕으로 잡스는 세계 최고 가치를 인정받는 기업을 만들었고, 기술 산업의 새로운 표준까지 정했다',
 '실리콘밸리에서 최근 뜨고 있는 스타 기업인 중에는 인문학 전공자들이 제법 많다',
 ' 구인·구직 소셜 네트워킹 서비스 기업인 링크드인(LinkedIn) 창업자 리드 호프만은 철학 석사 학위 소지자이며, 수잔 보이치키 유튜브 CEO는 역사와 문학을 전공했다',
 ' 메신저 개발 업체 슬랙(Slack)의 창업자 스튜어트 버터필드는 철학, 세계 최대 숙박 공유 기업인 에어비앤비의 설립자 브라이언 체스키는 미술을 전공했다',
 ' 중국 알리바바그룹의 마윈 회장의 학부 전공은 영어였다',
 '내가 속해 있는 하버드대·듀크대 연구팀은 미국 IT 기업 창업자들의 92%가 학사 학위를, 47%는 석사 학위 이상을 갖고 있음을 밝혀냈다',
 ' 창업자들의 세부 전공을 보면 37%만 공학·컴퓨터 기술이며, 수학 전공자는 2%뿐이었다',
 ' 이들의 전공은 경영·회계·보건·예술·인문학 등 매우 다양했다',
 '컴퓨터 주변기기 제조 업체 로지텍의 브랙큰 대럴 CEO도 영문학을 전공했다',
 ' 최근 내가 그에게 "어떻게 5년여 만에 회사 주가를 450% 올릴 수 있었느냐"고 물었더니 그는 "우리 회사가 만드는 모든 제품의 디자인을 쉼 없이 고민했기 때문에 가능했다',
 ' 기술 관련 제품의 성공에 가장 중요한 것은 디자인"이라고 답했다',
 "4차 산업혁명은 '혁신의 규칙'을 바꾸는 일이다",
 ' 여기에는 컴퓨터와 인공지능, 디지털 의술, 로봇공학, 합성생물학 등 광범위한 기술이 활용된다',
 " 의학·인공지능과 센서를 융합하면 인간의 건강을 진단하고 질병을 예방하는 '디지털 의사'를 만들 수 있다",
 ' 유전체학과 유전자 편집을 이용해 가뭄에 강하고 인류 전체를 먹여 살릴 새 식물을 개발할 수 있다',
 " 인공지능 로봇을 사용해 노인들을 위한 '디지털 친구'도 가능하다",
 " 초소형 물질의 발전은 모든 사람이 충분히 이용할 수 있는 '태양열 저장 기술'의 새 시대를 열 것이다",
 '이런 해결책을 이끌어내는 데는 생물학·교육·의료·인간행동 등 여러 분야에 대한 지식이 필요하다',
 ' 우리가 처한 거대한 사회·기술적 도전에 대처하려면 인류를 둘러싼 다양한 배경과 맥락에 대해 비판적 사고 능력이 필수적이다',
 ' 이는 인문학 전공자들이 가장 잘 훈련받은 분야이다',
 '일례로 음악·예술·문학과 심리학에서 비롯한 공감(共感) 능력은 디자인에 큰 장점이 된다',
 ' 로마제국의 흥망성쇠와 계몽주의를 공부한 역사학도는 기술의 인간적 요소와 유용성에 대한 통찰력을 가질 수 있다',
 ' 심리학 전공자는 사람에게 동기(動機)부여가 무엇이며, 사용자들이 원하는 게 무엇인지를 공학 한 분야에서만 일해온 엔지니어들보다 잘 이해할 수 있다',
 ' 우리가 상상하는 물건을 3D로 만들 수 있게 되면 음악가나 화가들의 세상이 될지도 모른다',
 '"자녀가 미래에 어떤 직업을 택하면 좋겠는가"라는 질문을 받을 때 나는 "아이들이 스스로 하고 싶은 것을 선택하도록 내버려 두는 게 최선"이라고 답한다',
 " 과거 우리 부모들이 우리에게 공부를 강요해서 학습을 '억지로 해야 하는 따분한 일'로 여기게 했던 방식을 따라 해선 안 된다",
 ' 그 대신 자녀가 자신의 열정을 추구하고 배우는 걸 즐길 수 있도록 북돋아야 한다',
 '기술을 통해 놀라운 미래를 창조하고 새로운 산업혁명 시대에 리더가 되기 위해 한국에서는 공학자들과 손잡고 일할 음악가와 화가가 더 많이 필요하다',
 ' 이제는 과학·공학·의학뿐 아니라 창의성과 디자인에도 진정한 관심을 쏟아야 한다',
 '']

In [0]:
tuned_sentences = []

for idx in range(len(sentences)) : 
    tuned_sentences.append(okt.nouns(sentences[idx]))
tuned_sentences[0]

['교육',
 '삶',
 '최',
 '우선',
 '순위',
 '한국',
 '부모',
 '대학',
 '전공',
 '가운데',
 '의학과',
 '공학',
 '과학',
 '중시']

In [0]:
tuned_sentences = [','.join(tuned_sentences[idx]).replace(',',' ') for idx in range(len(tuned_sentences))]
tuned_sentences

['교육 삶 최 우선 순위 한국 부모 대학 전공 가운데 의학과 공학 과학 중시',
 '자녀 직업 성공 위해 대학 전공 의학과 이공 우선 고려 일 한국 산업화 중 상황 선택',
 '지금 모든 것',
 '요즘 실리콘밸리 확인 것 차 산업혁명 시대 예술 인문학 의학 공학 사실',
 '스티브 잡스 자신 대학 시절 수강 서체 수업 매킨토시 애플 발표 개인 용 컴퓨터 개발 성공 영향 말',
 '그 아이패드 를 공개 애플 기술',
 '교양 인문학 결합 기술 가슴 결과 낳을 것 라며 예술 디자인 중요성 강조',
 '관점 바탕 잡스 세계 최고 가치 기업 기술 산업 표준 정',
 '실리콘밸리 최근 스타 기업인 중 인문학 전공자 제법',
 '구인 구직 소셜 네트워킹 서비스 기업인 링크드인 창업 리드 호프 철학 석사 학위 소지 잔 보이 유튜브 역사 문학 전공',
 '메신저 개발 업체 슬랙 의 창업 스튜어트 버터 필드 철학 세계 최대 숙박 공유 기업인 에어비앤비 설립 브라이언 체 스키 미술 전공',
 '중국 알리바바 그룹 마윈 회장 학부 전공 영어',
 '내 해 하버드대 듀크 팀 미국 기업 창업 자 학사 학위 석사 학위 이상 음',
 '창업 자 세부 전공 만 공학 컴퓨터 기술 수학 전공자',
 '이 전공 경영 회계 보건 예술 인문학 등 매우',
 '컴퓨터 주변기기 제조 업체 로지텍 브랙큰 대럴 도 영문학 전공',
 '최근 내 그 회사 주가 수 고 그 우리 회사 모든 제품 디자인 고민 때문',
 '기술 관련 제품 성공 가장 것 디자인 답',
 '차 산업혁명 혁신 규칙 일이',
 '여기 컴퓨터 인공 지능 디지털 의술 로봇공학 합성생물학 등 기술 활용',
 '의학 인공 지능 센서 융합 인간 건강 진단 질병 예방 디지털 의사 를 수',
 '유전체학 유전자 편집 이용 가뭄 인류 전체 새 식물 개발 수',
 '인공 지능 로봇 사용 노인 위 디지털 친구 도',
 '초소 물질 발전 모든 사람 이용 수 태양열 저장 기술 의 새 시대 열 것',
 '해결 책 데 생물학 교육 의료 인간 행동 등 여러 분야 대한 지식',
 '우리 처 사회 기술 도전 대처 인류 배경 맥락 대해 비판 사고 능력 필수',
 '인문학 전공자 가장 훈련 분야',
 '일례 음악 예술 문학 심리학 비롯 공감 능력 디자인 장점',
 '로마제국 흥망 성쇠 계몽 주의 공부 역사학도 기술 인간 요소 유용성 대한 통찰 수',
 '심리학 전공자 사람 동기 부여 무엇 사용자 게 무엇 인지 공학 분야 일 엔지니어 이해 수',
 '우리 상상 물건 로 수 음악가 화가 세상',
 '자녀 미래 직업 택하 질문 때 나 아이 스스로 것 선택 게 최선 답',
 '과거 우리 부모 우리 공부 강요 학습 억지로 일 로 여기 방식 해선 안',
 '그 대신 자녀 자신 열정 추구 걸 수 북',
 '기술 통해 미래 창조 산업혁명 시대 리더 위해 한국 공학자 일 음악가 화가 더',
 '이제 과학 공학 의학 창의성 디자인 관심',
 '']

In [0]:
vectorizer = TfidfVectorizer()
tfidf_vector = vectorizer.fit_transform(tuned_sentences).toarray()

In [0]:
luhn_importance = []

for idx in range(len(tfidf_vector)) : 
    luhn_importance.append(sum(tfidf_vector[idx]) / len([i for i in tfidf_vector[idx] if i != 0]))
luhn_importance[:5]

/home/hskimim/anaconda3/envs/dss_env/lib/python3.6/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in double_scalars
  after removing the cwd from sys.path.

[0.2864330566455741,
 0.2655826626486411,
 0.703848815311294,
 0.3138733801351376,
 0.24904542659640516]

In [0]:
final_df = pd.DataFrame(columns=['sentence','luhn_importance'])
final_df['sentence'] = sentences
final_df['luhn_importance'] = luhn_importance
final_df.sort_values('luhn_importance',ascending=False).head()

                                            sentence  luhn_importance
2                                 하지만 지금은 모든 것이 달라졌다         0.703849
18                        4차 산업혁명은 '혁신의 규칙'을 바꾸는 일이다         0.498424
5    그는 2011년 아이패드 2를 공개하면서 "애플의 DNA는 기술만으로는 충분하지 않다         0.489840
33      그 대신 자녀가 자신의 열정을 추구하고 배우는 걸 즐길 수 있도록 북돋아야 한다         0.445919
26                       이는 인문학 전공자들이 가장 잘 훈련받은 분야이다         0.444194

##LSA

In [0]:
|

In [0]:
import preprocessing_py as prep
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.pipeline import Pipeline
import numpy as np
import pandas as pd
from IPython.display import display , Markdown

In [0]:
import os

In [0]:
it_df = pd.read_csv('preprocessing_it.csv')
it_df.shape

(102, 3)

In [0]:
it_df = it_df.iloc[:,1:]
it_df.rename(columns={'0':'raw','1':'tuned'},inplace=True)
it_df['tuned'] = it_df['tuned'].apply(lambda x : x.replace(",",' '))

In [0]:
it_df.tail()

,raw,tuned
97,유영민 과학기술정통부 장관(오른쪽)이 22일 오후 서울 강서구 LG사이언스파크에서 ...,유영 민 과학기술 정통부 장관 오른쪽 오후 서울 강서구 사이언스 파크 중소기업 상생...
98,당당맨 최영수가 시사회 진행해 큰 인기(지디넷코리아=김민선 기자)애니메이션 &apo...,당당 맨 최영 수가 시사회 진행 인기 디 넷 코리아 김 민선 애니메이션 아이스 에이...
99,"전년比 4.9% 증가 '역대 최대'삼성전자, 최다 출원 5761건4차 산업혁명 시대...",전 년 증가 역대 최대 삼성 전자 최 출원 건 차 산업혁명 시대 핵심 자산 지식 재...
100,윤종인 행정안전부 차관(왼쪽 세번째)이 22일 오후 서울 종로구 정부서울청사에서 열...,윤 종인 행정 안전 부 차관 왼쪽 세 오후 서울 종로구 정부 서울 청사 블 록 체인...
101,[전자신문인터넷 박동선기자] 'K팝 명가' SM엔터테인먼트(이하 SM)가 4차 산업...,전자신문 인터넷 박동 선기 팝 명가 엔터테인먼트 이하 차 산업 기술 발전 발 차세대...

In [0]:
# raw documents to tf-idf matrix: 
vectorizer = TfidfVectorizer( use_idf=True, 
                             smooth_idf=True)
# SVD to reduce dimensionality: 
svd_model = TruncatedSVD(n_components=5,
                         algorithm='randomized',
                         n_iter=10)
# pipeline of tf-idf + SVD, fit to and applied to documents:
svd_transformer = Pipeline([('tfidf', vectorizer), 
                            ('svd', svd_model)])
# svd_matrix can later be used to compare documents, compare words, or compare queries with documentsa
documents = it_df['tuned'].tolist()
svd_matrix = svd_transformer.fit_transform(documents)

In [0]:
tfidf_encoding_vector = vectorizer.fit_transform(documents)
svd_matrix = svd_model.fit_transform(tfidf_encoding_vector)

In [0]:
print(svd_matrix.shape)
svd_matrix

(102, 5)

array([[ 2.60599236e-01, -3.97212865e-02,  4.20335502e-01,
         1.95781571e-01, -2.52184640e-01],
       [ 1.52032548e-01, -2.55084482e-02,  9.26432889e-03,
        -2.84366300e-02,  5.70541228e-02],
       [ 3.06213303e-01, -1.39739745e-01,  1.24294984e-01,
        -1.09839426e-01, -6.42499768e-02],
       [ 1.75708171e-01, -1.69289078e-02,  1.55163883e-01,
        -2.03451478e-01,  6.06721707e-02],
       [ 6.55834853e-02, -2.15937286e-02,  5.01504418e-02,
        -6.84057794e-02,  1.97128119e-01],
       [ 1.39988352e-01,  1.32835074e-02,  8.65993354e-02,
        -1.49371478e-01,  4.32390491e-02],
       [ 6.80485155e-02, -1.60572200e-02, -3.16402820e-03,
        -1.10582029e-02,  6.18490235e-01],
       [ 2.22799750e-01, -4.30826378e-02,  1.60023829e-01,
        -1.87357842e-01,  3.15073843e-01],
       [ 9.37675024e-02, -2.89161339e-02,  5.00652161e-02,
        -1.07601510e-01,  8.38490596e-02],
       [ 4.61334048e-01,  7.24005787e-01, -1.19768114e-01,
         3.91726459e-02, -3.50548836e-02],
       [ 1.00222292e-01, -8.00318257e-03,  1.39197274e-01,
        -6.51430707e-02, -1.23815767e-03],
       [ 9.34250587e-02, -1.61018430e-03,  7.25019268e-02,
        -7.50119034e-02, -2.56728536e-03],
       [ 1.23446883e-01,  1.83306758e-02,  6.26868966e-02,
        -8.99601302e-02,  1.00908898e-02],
       [ 1.43328230e-01, -2.81506392e-02,  1.57906037e-01,
        -1.06388697e-01, -3.39779986e-02],
       [ 4.53664228e-01,  6.99562081e-01, -7.78348444e-02,
         1.81835519e-02, -1.66247067e-02],
       [ 1.47914203e-01, -4.49925919e-02,  5.13980781e-01,
         6.56683101e-01,  2.16338890e-01],
       [ 9.00166782e-02, -7.83763374e-03,  5.33699074e-02,
        -1.02191868e-01,  2.22360789e-02],
       [ 5.46405264e-01, -3.44370725e-01, -2.07333425e-01,
         5.18050597e-02, -1.48456512e-01],
       [ 1.10814165e-01,  2.74819452e-03,  5.79637583e-02,
        -4.63970125e-02,  9.42564522e-02],
       [ 1.27433472e-01,  1.81001893e-02,  4.53083841e-02,
        -9.91385022e-02,  1.69537463e-01],
       [ 2.55073883e-01, -1.06232463e-02,  1.81202855e-01,
        -1.56262598e-01,  2.65599682e-02],
       [ 1.59905508e-01, -7.62248771e-02, -1.38586323e-02,
        -5.41508041e-02,  1.99098372e-01],
       [ 4.57556106e-01,  7.23300177e-01, -1.19200565e-01,
         3.15562642e-02, -3.42536955e-02],
       [ 1.44039045e-01, -4.68892382e-03,  7.00636847e-02,
        -1.03632833e-01,  8.12451350e-02],
       [ 1.38887585e-01, -2.41254322e-02,  9.47073266e-02,
        -1.53844876e-01,  3.68491665e-02],
       [ 1.04217357e-01,  5.74488930e-03, -1.04768170e-02,
        -2.83544120e-02,  1.64993995e-02],
       [ 7.47599617e-02, -1.47732189e-02,  5.30258058e-02,
        -9.02061572e-02,  1.64319358e-01],
       [ 2.70100157e-01, -6.61723905e-02,  4.37691179e-01,
         1.25499953e-01, -3.28829840e-01],
       [ 2.59382603e-01, -1.16678195e-01,  2.37637680e-01,
        -1.02857717e-01, -1.85845205e-01],
       [ 1.30141246e-01, -2.53188113e-02,  2.37813617e-01,
        -1.33683017e-02, -6.53085858e-03],
       [ 7.65775750e-02, -3.46194556e-03,  7.41367655e-02,
        -8.22884293e-02,  2.51482483e-02],
       [ 1.44985869e-01, -2.08016843e-02,  1.02119966e-01,
        -1.58079235e-01,  5.85481078e-03],
       [ 2.86662353e-01, -1.31302217e-01,  2.75016943e-01,
        -1.12681040e-01, -2.34217343e-01],
       [ 2.15504936e-01, -7.61692626e-02,  3.08470226e-01,
         5.79263510e-03, -1.78732860e-01],
       [ 2.72366272e-01, -9.70165180e-02,  2.14769160e-01,
        -3.47806053e-01,  2.56745917e-02],
       [ 3.96277055e-01,  5.60761586e-01, -5.69326132e-02,
        -9.01656674e-03,  5.70686356e-04],
       [ 3.98621868e-01, -2.38781991e-01, -2.04359736e-01,
         9.56987201e-02,  4.06159356e-01],
       [ 3.98621868e-01, -2.38781991e-01, -2.04359736e-01,
         9.56987201e-02,  4.06159356e-01],
       [ 6.80485155e-02, -1.60572200e-02, -3.16402820e-03,
        -1.10582029e-02,  6.18490235e-01],
       [ 2.22799750e-01, -4.30826378e-02,  1.60023829e-01,
        -1.87357842e-01,  3.15073843e-01],
       [ 9.73913451e-02, -7.72604800e-03,  3.87072021e-02,
        -4.64574745e-02,  2.03362246e-02],
       [ 6.22328259e-02, -3.75569050e-03,  2.13192515e-02,
        -3.76204484e-02,  1.77853564e-02],
       [ 8.16892230e-02, -3.37798203e-02,  2.51677351e-02,
        -9.69018996e-02,  8.11951777e-02],
       [ 8.58792772e-02, -2.65270818e-02,  4.27395383e-02,
        -1.05428465e-01,  4.19461613e-02],
       [ 1.31091665e-01, -3.75539920e-02,  7.56416352e-02,
        -1.63873462e-01,  4.25842802e-02],
       [ 5.65520926e-01, -3.64122700e-01, -2.46184587e-01,
         1.12307908e-01, -9.20326687e-02],
       [ 7.49698895e-02, -2.63150315e-02,  4.50114127e-02,
        -9.05418601e-02,  4.20351968e-02],
       [ 1.33663698e-01, -2.61445423e-02,  6.72968020e-02,
        -1.55352371e-01,  4.10501378e-02],
       [ 1.24753530e-01, -2.89008555e-02,  2.36278671e-01,
        -1.00279279e-02, -1.10477960e-02],
       [ 1.46925796e-01, -4.60495390e-02,  5.26032579e-01,
         6.84311954e-01,  2.12453478e-01],
       [ 2.73657926e-01, -7.12418005e-02,  4.73783747e-01,
         1.74078641e-01, -3.00863905e-01],
       [ 8.18721392e-02, -4.46434057e-03,  1.07279639e-01,
        -2.24417240e-02,  1.17985278e-01],
       [ 1.43747809e-01, -4.61299610e-02,  3.50561073e-01,
         2.23273203e-01,  6.24323460e-02],
       [ 4.94640635e-01, -3.21825023e-01, -3.42812905e-01,
         1.97820870e-01, -7.63153917e-02],
       [ 1.43146950e-01, -4.80462667e-02,  1.24276998e-01,
        -1.16026112e-01, -6.74401920e-02],
       [ 4.22088686e-01,  6.05996870e-01, -7.65885086e-02,
         1.94898336e-03,  1.44306344e-02],
       [ 2.14432981e-01, -8.50303312e-02,  9.74594850e-02,
        -2.41783388e-01,  9.49262536e-02],
       [ 1.50367556e-01, -6.28799750e-02,  1.41825259e-01,
        -8.43517416e-02,  1.70817195e-02],
       [ 9.37815915e-02, -2.40794746e-02,  7.61025120e-02,
        -1.41446965e-01,  7.88896864e-02],
       [ 1.53642198e-01, -5.00691764e-02,  1.14230808e-01,
        -1.28861088e-01,  1.82034472e-02],
       [ 1.07991989e-01, -4.81805970e-02,  3.13617755e-02,
        -1.21331831e-01,  7.50463703e-02],
       [ 6.26954100e-01, -3.97849026e-01, -3.22516825e-01,
         1.57017746e-01, -8.76845853e-02],
       [ 4.35302840e-01,  6.95845928e-01, -7.98128515e-02,
         4.37192729e-02, -2.42948839e-02],
       [ 1.36356039e-01, -4.70136249e-02,  4.95359254e-01,
         6.73450709e-01,  2.28646370e-01],
       [ 5.94890468e-01, -3.81755083e-01, -2.99128884e-01,
         9.45025454e-02, -1.02223354e-01],
       [ 5.50061298e-01, -3.28841253e-01, -3.15396464e-01,
         1.64528671e-01, -2.41502842e-02],
       [ 2.81283890e-01, -9.76966556e-02,  1.91344106e-01,
        -3.45936703e-01,  4.99546030e-02],
       [ 3.79757826e-01,  5.91106523e-01, -6.17869393e-02,
         4.21605987e-02,  1.00849757e-02],
       [ 2.29362695e-01, -1.18554276e-02,  1.92610335e-01,
        -1.16250198e-01,  5.23234532e-02],
       [ 1.10389373e-01, -1.10959937e-02,  5.67537118e-02,
        -1.01199107e-01,  1.25600686e-01],
       [ 1.24408834e-01, -4.81100052e-02,  1.42517643e-01,
        -9.94172269e-02,  3.96843029e-03],
       [ 4.14495639e-01,  6.74997494e-01, -6.94144195e-02,
         8.10158347e-02, -1.66112841e-02],
       [ 1.10938937e-01, -7.81836974e-03,  5.57696257e-02,
        -1.20320680e-01,  2.12854345e-02],
       [ 1.82645666e-01, -3.35730524e-02,  9.83387883e-02,
        -1.94887279e-01,  3.20126707e-02],
       [ 6.55824905e-01, -3.88590042e-01, -3.06557301e-01,
         1.09713884e-01, -1.19302808e-01],
       [ 9.29982893e-02, -2.71028335e-02,  2.13873999e-02,
        -1.69000394e-02,  2.70425634e-02],
       [ 8.14267309e-02, -3.72960200e-02,  3.12900250e-02,
        -7.68733773e-02,  4.32285461e-02],
       [ 1.64172168e-01, -3.99144415e-02,  1.34075177e-01,
        -1.62293441e-01,  5.89960112e-03],
       [ 1.18834722e-01,  5.73673370e-03,  6.91823248e-02,
        -1.04141102e-01, -5.12494834e-02],
       [ 1.43421002e-01, -6.99684359e-02,  6.15487111e-02,
        -6.44085129e-03, -6.21264537e-02],
       [ 2.92251924e-01, -1.18137845e-01,  2.41093810e-01,
        -2.54474456e-01, -1.03290654e-01],
       [ 1.37425175e-01, -4.60588916e-02,  8.71593728e-02,
        -1.43589458e-01, -3.46574712e-03],
       [ 1.02041478e-01, -3.63806601e-02,  8.13727961e-02,
        -1.66468709e-01,  2.00860344e-02],
       [ 9.81840887e-02, -1.00128679e-02,  6.56109276e-02,
        -1.18152696e-01, -3.73921318e-02],
       [ 2.65354173e-01, -1.02414897e-01,  2.08990550e-01,
        -1.21484948e-01, -1.30130373e-01],
       [ 1.19970583e-01, -3.08382259e-02,  1.03060339e-01,
        -1.75713097e-01, -3.64071968e-03],
       [ 4.34434740e-01,  7.03519517e-01, -8.11678444e-02,
         8.18185153e-02, -2.42853610e-02],
       [ 2.41571228e-01, -1.00260576e-01,  2.96443715e-01,
        -4.96302112e-02, -1.67135973e-01],
       [ 1.11567931e-01, -3.55541883e-02,  6.67480598e-02,
        -1.13687690e-01, -1.87224357e-04],
       [ 1.34564578e-01, -5.56268342e-02,  1.61015659e-01,
        -3.53455254e-02, -4.75304070e-02],
       [ 4.99694314e-01, -3.46611414e-01, -3.38898196e-01,
         1.48940489e-01, -7.10051422e-02],
       [ 8.04651004e-02, -1.90695998e-02,  5.34548933e-02,
        -5.25138772e-02,  2.31841187e-01],
       [ 1.55928560e-01, -3.89949369e-02,  1.28221937e-01,
        -2.13365458e-01, -1.92617967e-02],
       [ 1.41465219e-01,  6.79544470e-02,  1.19841500e-01,
         8.50081936e-02,  6.63679796e-02],
       [ 1.55540616e-01, -8.59293312e-02,  9.14199321e-02,
        -3.79066756e-02, -9.16394325e-03],
       [ 1.53604605e-01, -1.59480248e-02,  8.71079362e-02,
        -1.43467564e-01,  8.30933424e-02],
       [ 1.57272277e-01, -5.93480633e-02,  4.50667463e-02,
        -9.17599636e-02,  1.74262675e-01],
       [ 5.01969869e-01, -3.15047988e-01, -2.97243258e-01,
         1.16070974e-01,  2.27602683e-03],
       [ 6.21465093e-02, -3.42890498e-02, -9.87114286e-03,
        -1.57994796e-02,  3.31911078e-02],
       [ 1.29435743e-01, -4.81791086e-02,  5.73164356e-02,
        -8.74807037e-02, -1.04471566e-02],
       [ 1.61452022e-01, -4.47816026e-02,  9.27248042e-02,
        -5.11591818e-02,  5.68422595e-02],
       [ 2.11158718e-01, -6.63241562e-02,  1.24835171e-01,
        -1.50553196e-01,  2.95322091e-02]])

In [0]:
cluster_ls = []
for idx in range(len(svd_matrix)) :
    cluster_ls.append((it_df['raw'][idx],np.argmax(svd_matrix[idx]),np.max(svd_matrix[idx])))

In [0]:
print(cluster_ls[0][0])

배정회 신임 과학기술일자리진흥원장[아시아경제 이민우 기자] 배정회 전 국립중앙과학관전시연구단장(56)이 과학기술일자리진흥원 제3대 원장으로 취임했다.과학기술정보통신부는 22일 이 같은 인사를 발표했다. 임기는 이날부터 3년 동안이다.배 신임 원장은 행정고등고시 40회로 공직에 입문했다. 교육과학기술부 융합기술과장, 중앙대 경영경제대 초빙교수, 과기정통부연구성과활용정책과장 및 연구성과혁신기획과장 등을 거쳤다. 과학기술 정책 수립부터 정부 연구개발(R&D;), 연구성과의 기술 이전 및 사업화까지 두루 경험을 보유한 것으로 평가받는다.배 신임 원장은 이날 환담회에서 "새로운 임무에 맞게 조직을 신속히 재구성하고 직원 역량을 강화하겠다'며 "실험실 유망기술을 R&D; 전문기업과 연결하며 기술이전을 효과적으로 지원하고 신기술창업을 통한 미래형 일자리를 많이 창출시키겠다"고 밝혔다.이민우 기자 letzwin@asiae.co.kr▶ 네이버 홈에서 '아시아경제' 뉴스 확인하기▶ 재미와 신기 '과학을읽다' ▶ 꿀잼 '인기만화'<ⓒ경제를 보는 눈, 세계를 보는 창 아시아경제 무단전재 배포금지>

In [0]:
print(cluster_ls[0][1])

2

In [0]:
cluster_ls = []
for idx in range(len(svd_matrix)) :
    cluster_ls.append((it_df['raw'][idx],np.argmax(svd_matrix[idx]),np.max(svd_matrix[idx])))

new_ls = [i[0] for i in cluster_ls]
cat_ls = [i[1] for i in cluster_ls]
score_ls = [i[2] for i in cluster_ls]

lsa_df = pd.DataFrame()
lsa_df['news'] = new_ls
lsa_df['cat'] = cat_ls
lsa_df['score'] = score_ls

for i in range(5) :
    if \
    len(lsa_df[lsa_df['cat'] == i].sort_values('score',ascending=False).head(5)) == 0 :
        display(Markdown('### There is no data which belong to {}-th cat!'.format(i+1)))

    else :display(lsa_df[lsa_df['cat'] == i].sort_values('score',ascending=False).head(5))

                                                 news  cat     score
74  LG 사이언스파크에서 5G 준비현황 점검 후 업계 의견 청취유영민 장관 "5G시대 ...    0  0.655825
61  [머니투데이 김주현 기자] [3개부처 장관, LG 5G 현장방문…유영민 장관 "통신...    0  0.626954
64  LG유플러스가 준비 중인 5G 서비스에 대한 전시와 시연에서 성윤모 산업통상자원부장...    0  0.594890
45  유영민 과학기술정보통신부장관(가운데)과 성윤모 산업통상자원부장관(왼쪽), 홍종학 중...    0  0.565521
65  과기·산업·중기장관 등 마곡 방문유영민(왼쪽 세번째) 과학기술정보통신부 장관, 성윤...    0  0.550061

                                                 news  cat     score
9   KT스카이라이프 "세부 내용은 확인 필요"국회 과방위, 합산규제 문제 2월 재논의【...    1  0.724006
22  과기정통부.KT 공공성 회복 방안 검토 후 다시 논의【서울=뉴시스】이국현 기자 = ...    1  0.723300
86  김성태 의원 "KT스카이라이프 공공성 확보 방안, 과기정통부에 요청…합산규제 재도입...    1  0.703520
14  과방위, 규제 유지 쪽으로 기울어향후 M&A; 등 사업확장 걸림돌22일 국회 과학기...    1  0.699562
62  [아시아경제 명진규 기자] 국회 과학기술정보방송통신위원회(이하 과방위)는 22일 법...    1  0.695846

                                                 news  cat     score
50  [이데일리 이연호 기자] 과학기술정보통신부는 배정회(57·사진) 전 국립중앙과학관 ...    2  0.473784
27  배정회 과기일자리진흥원장배정회 과학기술일자리진흥원 원장(앞줄 왼쪽 네번째)이 22일...    2  0.437691
0   배정회 신임 과학기술일자리진흥원장[아시아경제 이민우 기자] 배정회 전 국립중앙과학관...    2  0.420336
52  [이데일리 이연호 기자] △정책부장 김강회 △기획부장 송장헌 △연구데이터공유센터장 ...    2  0.350561
33  석제범 IITP 원장 간담회석제범 정보통신기획평가원장"이노베이션 아카데미, AI대학...    2  0.308470

                                                 news  cat     score
49  [이데일리 이연호 기자]◇직책승진(8명)△감사부 부장 변재규△창의융합교육단 단장 허...    3  0.684312
63  <직책 승진>Δ변재규 감사부 부장 Δ허경호 창의융합교육단 단장Δ 김명수 과학문화산업...    3  0.673451
15  ◇한국과학창의재단 ◇승진 △감사부장 변재규 △창의융합교육단장 허경호(종합교육연수원장...    3  0.656683

                                                 news  cat     score
6                                              동영상 뉴스    4  0.618490
38                                             동영상 뉴스    4  0.618490
36  (서울=연합뉴스) 성윤모 산업통상자원부 장관이 22일 오후 서울 강서구 마곡동 LG...    4  0.406159
37  (서울=연합뉴스) 성윤모 산업통상자원부 장관이 22일 오후 서울 강서구 마곡동 LG...    4  0.406159
7    [앵커] 검색 기록과 내비게이션 이동경로까지, 일상 속 수많은 정보가 쌓여 '빅 ...    4  0.315074